
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HibernateWebService", targetNamespace = "http://hibernatewebservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HibernateWebService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "insertNew", targetNamespace = "http://hibernatewebservice/", className = "service.InsertNew")
    @ResponseWrapper(localName = "insertNewResponse", targetNamespace = "http://hibernatewebservice/", className = "service.InsertNewResponse")
    @Action(input = "http://hibernatewebservice/HibernateWebService/insertNewRequest", output = "http://hibernatewebservice/HibernateWebService/insertNewResponse")
    public void insertNew(
        @WebParam(name = "arg0", targetNamespace = "")
        Account arg0);

    /**
     * 
     * @return
     *     returns java.util.List<service.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get", targetNamespace = "http://hibernatewebservice/", className = "service.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://hibernatewebservice/", className = "service.GetResponse")
    @Action(input = "http://hibernatewebservice/HibernateWebService/getRequest", output = "http://hibernatewebservice/HibernateWebService/getResponse")
    public List<Account> get();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://hibernatewebservice/", className = "service.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://hibernatewebservice/", className = "service.DeleteResponse")
    @Action(input = "http://hibernatewebservice/HibernateWebService/deleteRequest", output = "http://hibernatewebservice/HibernateWebService/deleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        Account arg0);

}
