
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestWebService1", targetNamespace = "http://testwebservice1/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestWebService1 {


    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "download", targetNamespace = "http://testwebservice1/", className = "service.Download")
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://testwebservice1/", className = "service.DownloadResponse")
    @Action(input = "http://testwebservice1/TestWebService1/downloadRequest", output = "http://testwebservice1/TestWebService1/downloadResponse")
    public byte[] download(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "upload", targetNamespace = "http://testwebservice1/", className = "service.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://testwebservice1/", className = "service.UploadResponse")
    @Action(input = "http://testwebservice1/TestWebService1/uploadRequest", output = "http://testwebservice1/TestWebService1/uploadResponse")
    public void upload(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1);

}
