
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestWebService1Service", targetNamespace = "http://testwebservice1/", wsdlLocation = "http://localhost:8987/image?wsdl")
public class TestWebService1Service
    extends Service
{

    private final static URL TESTWEBSERVICE1SERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTWEBSERVICE1SERVICE_EXCEPTION;
    private final static QName TESTWEBSERVICE1SERVICE_QNAME = new QName("http://testwebservice1/", "TestWebService1Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8987/image?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTWEBSERVICE1SERVICE_WSDL_LOCATION = url;
        TESTWEBSERVICE1SERVICE_EXCEPTION = e;
    }

    public TestWebService1Service() {
        super(__getWsdlLocation(), TESTWEBSERVICE1SERVICE_QNAME);
    }

    public TestWebService1Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTWEBSERVICE1SERVICE_QNAME, features);
    }

    public TestWebService1Service(URL wsdlLocation) {
        super(wsdlLocation, TESTWEBSERVICE1SERVICE_QNAME);
    }

    public TestWebService1Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTWEBSERVICE1SERVICE_QNAME, features);
    }

    public TestWebService1Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWebService1Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestWebService1
     */
    @WebEndpoint(name = "TestWebService1Port")
    public TestWebService1 getTestWebService1Port() {
        return super.getPort(new QName("http://testwebservice1/", "TestWebService1Port"), TestWebService1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWebService1
     */
    @WebEndpoint(name = "TestWebService1Port")
    public TestWebService1 getTestWebService1Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://testwebservice1/", "TestWebService1Port"), TestWebService1.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTWEBSERVICE1SERVICE_EXCEPTION!= null) {
            throw TESTWEBSERVICE1SERVICE_EXCEPTION;
        }
        return TESTWEBSERVICE1SERVICE_WSDL_LOCATION;
    }

}
