package com.shibo.models;
// Generated Mar 22, 2017 9:43:59 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Teacher generated by hbm2java
 */
public class Teacher extends Person implements java.io.Serializable {


        private Date hireDate;

    public Teacher() {
    }

    public Teacher(Date hireDate) {
      
     
       this.hireDate = hireDate;
    }
   
   
   
    public Date getHireDate() {
        return this.hireDate;
    }
    
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }




}


